SKILLS = [
    "python",
    "java",
    "c",
    "c++",
    "javascript",
    "typescript",
    "html",
    "css",
    "react",
    "angular",
    "vue",
    "nodejs",
    "express",
    "mongodb",
    "mysql",
    "sql",
    "postgresql",
    "oracle",
    "firebase",
    "aws",
    "azure",
    "gcp",
    "docker",
    "kubernetes",
    "git",
    "github",
    "linux",
    "tensorflow",
    "keras",
    "pytorch",
    "opencv",
    "machine learning",
    "deep learning",
    "nlp",
    "computer vision",
    "pandas",
    "numpy",
    "matplotlib",
    "seaborn",
    "power bi",
    "tableau",
    "excel",
    "hadoop",
    "spark",
    "flask",
    "django",
    "rest api",
    "fastapi"
]